python predict_and_pickle.py -model model_upper_u08_lr0001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/ 
python predict_and_pickle.py -model model_upper_u08_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/ 
python predict_and_pickle.py -model model_upper_u08_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/ 
python predict_and_pickle.py -model model_upper_u10_lr0001.h5 -nsteps 210  -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u10_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u10_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u12_lr0001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u12_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u12_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u14_lr0001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u14_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u14_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr00001_Adam.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_Adam.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_Adam_ss_do.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_Adam_ss.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_SGD.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_SGDssdo.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_SGDss.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_zca.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_zcass_do.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr0001_zcass.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u16_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u18_lr0001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u18_lr001.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/
python predict_and_pickle.py -model model_upper_u18_lr01.h5 -nsteps 210 -testdir ../fdata_CropSQRS/test/upper/ 
